/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ohhoonim.java.advanced;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertEquals("app should have a greeting", "app should have a greeting");
    }
}
